name: NextJS

on:
  push:
    branches:
      - main
    paths-ignore:
      - packages/fastapi/**
      - packages/tact/**
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run format
        run: pnpm nextjs:format:check

      - name: Run lint
        run: pnpm nextjs:lint --max-warnings=0

      - name: Run Typescript linter
        run: pnpm nextjs:ts

      - name: Notify on failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ vars.TELEGRAM_UPDATES_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ NextJS. Tests/Lint failed

            Commit message: ${{ github.event.commits[0].message }}
            https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}

  deploy:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: deploy
      name: Deploy to dokku
      uses: dokku/github-action@v1.1.3
      with:
          git_push_flags: '--force'
          git_remote_url: ${{ secrets.NEXTJS_DEPLOY_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Notify on failure
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ vars.TELEGRAM_UPDATES_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ❌ NextJS. Deploy failed

          Commit message: ${{ github.event.commits[0].message }}
          https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}
    - name: Notify on success
      if: ${{ success() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ vars.TELEGRAM_UPDATES_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ✅ NextJS. Deploy succeed

          Commit message: ${{ github.event.commits[0].message }}
          https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}
