name: Tact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Install dependencies
        run: pnpm install

      - name: Build smartcontracts
        run: yarn next:build

      - name: Run tests
        run: yarn tact:test

      - name: Run hardhat lint
        run: yarn hardhat:lint --max-warnings=0
