version: "3.8"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: g2g_db
    command: postgres -c log_statement=all
    restart: always
    volumes:
      - ./.db/:/var/lib/postgresql/data/
      - ./scripts/create_multiple_postgresql_databases.sh:/docker-entrypoint-initdb.d/09_create_multiple_postgresql_databases.sh
      - ./scripts/enable_db_extensions.sh:/docker-entrypoint-initdb.d/20_enable_db_extensions.sh
    environment:
      - POSTGRES_MULTIPLE_DATABASES=db,db_test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password123
    ports:
      - 5435:5432  # exposed 5435 port for avoiding conflicts with another db

  minio:
    image: minio/minio:latest
    container_name: g2g_minio
    entrypoint: sh
    command: -c 'mkdir -p /data/g2g && /usr/bin/docker-entrypoint.sh server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./.minio:/data/
    ports:
      - 9000:9000
      - 9001:9001
