version: "3.8"

services:
  db:
    image: postgres:16.1
    container_name: g2g_db
    command: postgres -c log_statement=all
    restart: always
    volumes:
      - ./.db/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password123
    ports:
      - 5435:5432  # exposed 5435 port for avoiding conflicts with another db
